-- Stage C wave 2: legacy business rules of the Accounts Payable data-entry screens
--   VNDBTRN     supplier debit transactions (payments / settlements)        VN_MAINTRNS + VN_SUBTRNS (payment lines) + accounts
--   VNCRTRN     supplier credit transactions (manual invoices / settlements) VN_MAINTRNS + VN_SUBTRNS (invoice lines) + accounts
--   VNCRTRN_ST  credit transactions generated by other systems (view / adjust only)
--   VNDBTRN_ST  debit transactions generated by other systems (view / adjust only)
--   VNCHECKPAY  supplier cheque payment requests                          VN_MAINTRNS_CHECK + VN_SUBTRNS_CHECK
-- Called from app\legacy\overrides\<FORM>.json (key_expr / row_rules / validations / after_save).
-- Evidence and rule list: app\legacy\processes\<FORM>.md.  Messages are the legacy Arabic texts where one existed.
-- Not duplicated here (existing DB triggers): CLOSE_VN_MAINTRNS (closed period vs AC_BASIC), VN_MAINTRNS_TAX /
-- VN_SUBTRNS_TAX (tax-period lock), VN_MAINTRNS_ALTKEY (ALT_KEY, ACC_POST_DATE default).
-- Wave 3: RESIDUAL_VALUE of the invoice lines paid by a debit document (VN_SUBTRNS PRE-INSERT / DELETE_DETAIL_EFFECT);
-- the buttons and displays of the AP screens are in APP_ACT_PR (23_act_pr.sql).
set define off

create or replace package app_rules_vn as
  -- conversions of APEX page-item strings (application date format DD/MM/YYYY)
  function num(p varchar2) return number;
  function dt(p varchar2) return date;
  function differs(p_new number, p_old number) return number;
  function differs(p_new date, p_old date) return number;

  -- numbering (VNDBTRN / VNCRTRN PRE-INSERT): max(TRNS_SERIAL)+1 per TRNS_ID and VN_TRNSTYPE.LAST_SERIAL := new serial
  function next_trns_serial(p_trns_id number) return number;

  -- screen membership of a transaction type (legacy block WHERE / TRNSTYPE record groups), 1 = allowed
  function type_allowed(p_form varchar2, p_trns_id number) return number;
  function default_trns_id(p_form varchar2) return number;
  function default_pay_type return number;
  function supplier_resp(p_supplier_id number) return number;

  -- derivations used by row rules
  function payment_desc_e(p_trns_id number, p_desc_e varchar2, p_doc_no number, p_pay_method number, p_acc_post_date date) return varchar2;
  procedure calc_tax(p_trns_id number, p_supplier_id number, p_trns_date date, p_value number,
                     p_tax_code in out number, p_tax_value in out number);
  function total_with_tax(p_trns_id number, p_supplier_id number, p_value number, p_tax1 number, p_tax2 number) return number;
  procedure acc_line(p_acc_number number, p_acc_val number, p_cost_center number, p_cost_center2 number);
  function supp_acc_memo(p_trns_id number, p_trns_serial number, p_memo varchar2) return varchar2;
  function band_supplier(p_trns_id number, p_trns_serial number) return number;

  -- page validations (function bodies return the Arabic error text or null)
  function check_header(p_form varchar2, p_request varchar2, p_rowid varchar2, p_trns_id varchar2, p_supplier_id varchar2,
                        p_trns_date varchar2, p_acc_post_date varchar2, p_doc_no varchar2, p_currency_code varchar2,
                        p_currency_rate varchar2, p_inv_value varchar2 default null) return varchar2;
  function check_st(p_form varchar2, p_rowid varchar2, p_doc_no varchar2) return varchar2;

  -- after-save checks / derivations (raise -20100..-20199 to roll the whole save back)
  procedure after_save(p_form varchar2, p_rowid varchar2, p_request varchar2);
  procedure check_gl_link(p_trns_id number, p_trns_serial number);
  procedure on_delete(p_form varchar2, p_trns_id varchar2, p_trns_serial varchar2, p_post_flag varchar2,
                      p_pay_flag varchar2, p_link_flag varchar2 default null);

  -- VNCHECKPAY
  procedure checkpay_supplier_info(p_supplier_id number, p_supplier_bal in out number, p_db_cr_flag in out varchar2,
                                   p_db_cr_flag_e in out varchar2, p_check_hold in out number, p_currency_code in out number,
                                   p_currency_rate in out number, p_resp_code in out number);
  function check_checkpay(p_request varchar2, p_rowid varchar2, p_supplier_id varchar2, p_from_date varchar2, p_to_date varchar2,
                          p_due_date varchar2, p_doc_no varchar2, p_currency_code varchar2, p_currency_rate varchar2,
                          p_due_disc varchar2, p_auth_flag varchar2) return varchar2;
  procedure after_save_checkpay(p_rowid varchar2, p_request varchar2);
  procedure on_delete_checkpay(p_serial varchar2, p_auth_flag varchar2);
end app_rules_vn;
/

create or replace package body app_rules_vn as

  procedure err(p_code pls_integer, p_msg varchar2) is
  begin
    raise_application_error(p_code, p_msg);
  end;

  function num(p varchar2) return number is
  begin
    if p is null then return null; end if;
    return to_number(replace(trim(p), ',', ''));
  exception when others then
    return null;
  end;

  function dt(p varchar2) return date is
  begin
    if p is null then return null; end if;
    begin return to_date(p, 'DD/MM/YYYY'); exception when others then null; end;
    begin return to_date(p, 'DD-MM-YYYY'); exception when others then null; end;
    begin return to_date(substr(p, 1, 10), 'YYYY-MM-DD'); exception when others then null; end;
    return null;
  end;

  function differs(p_new number, p_old number) return number is
  begin
    return case when (p_new is null and p_old is null) or p_new = p_old then 0 else 1 end;
  end;

  function differs(p_new date, p_old date) return number is
  begin
    return case when (p_new is null and p_old is null) or p_new = p_old then 0 else 1 end;
  end;

  function pw return number is
  begin
    return nvl(num(v('G_PASSWORD_NUMBER')), 0);
  end;

  function has_rap_chk_sys return boolean is
    l number;
  begin
    select count(*) into l from sys_systems where system_number in (13, 15);   -- SET_RP_CK_SYS
    return l > 0;
  end;

  -- ------------------------------------------------------------------ numbering
  function next_trns_serial(p_trns_id number) return number is
    l_serial number;
    l_dummy  number;
  begin
    -- the legacy PRE-INSERT updated VN_TRNSTYPE.LAST_SERIAL in the same transaction, which also serialised
    -- concurrent saves of the same type; the row lock below keeps that behaviour
    begin
      select last_serial into l_dummy from vn_trnstype where id = p_trns_id for update;
    exception when no_data_found then
      null;
    end;
    select nvl(max(trns_serial), 0) + 1 into l_serial from vn_maintrns where trns_id = p_trns_id;
    update vn_trnstype set last_serial = l_serial where id = p_trns_id;
    return l_serial;
  end;

  -- ------------------------------------------------------------------ types / defaults
  function type_allowed(p_form varchar2, p_trns_id number) return number is
    l    number;
    l_pw number := pw;
  begin
    select count(*) into l
      from vn_trnstype t
     where t.id = p_trns_id
       and (   (p_form = 'VNDBTRN'    and t.effect = 0 and t.trns_type <> 5 and nvl(t.sum_trns, 0) = 0)
            or (p_form = 'VNCRTRN'    and t.effect = 1 and t.trns_type <> 5 and nvl(t.sum_trns, 0) = 0)
            or (p_form = 'VNDBTRN_ST' and t.effect = 0 and t.trns_type <> 5)
            or (p_form = 'VNCRTRN_ST' and t.effect = 1))
       and (l_pw = 0 or t.id in (select p.trns_id from vn_trnstype_password p where p.flag = 1 and p.password_number = l_pw));
    return case when l > 0 then 1 else 0 end;
  end;

  function default_trns_id(p_form varchar2) return number is
    l number;
  begin
    -- VNDBTRN: first payment type (201 "سداد الى الموردين"); VNCRTRN: first settlement type (103) - the types used manually
    select min(id) into l
      from vn_trnstype
     where nvl(sum_trns, 0) = 0
       and ((p_form = 'VNDBTRN' and effect = 0 and trns_type = 1)
         or (p_form = 'VNCRTRN' and effect = 1 and trns_type = 4));
    return l;
  end;

  function default_pay_type return number is
    l number;
  begin
    select min(pay_type_code) into l from vn_basic;
    if l is null then
      select min(settel_type_code) into l from lc_settel_type where nvl(non_pay_flag, 0) = 0;
    end if;
    return l;
  exception when others then
    return null;
  end;

  function supplier_resp(p_supplier_id number) return number is
    l number;
  begin
    if p_supplier_id is null then return null; end if;
    select min(code) into l from vn_supp_resp where supp_code = p_supplier_id;   -- SUPPLIER_ID WHEN-VALIDATE-ITEM
    return l;
  end;

  -- ------------------------------------------------------------------ derivations
  function payment_desc_e(p_trns_id number, p_desc_e varchar2, p_doc_no number, p_pay_method number, p_acc_post_date date) return varchar2 is
    l_type   number;
    l_effect number;
    l_desc   varchar2(4000) := p_desc_e;
  begin
    -- VNDBTRN PRE-INSERT: payments (TRNS_TYPE 1, EFFECT 0) carry the supplier document number in DESCRIPTION_E
    select trns_type, effect into l_type, l_effect from vn_trnstype where id = p_trns_id;
    if l_type = 1 and l_effect = 0 then
      if l_desc is not null then
        l_desc := l_desc || ' - ';
      end if;
      l_desc := l_desc || ' رقم سند المورد ' || p_doc_no;
      if p_pay_method = 4 then
        l_desc := l_desc || ' تاريخ الشيك ' || to_char(p_acc_post_date, 'DD-MM-RRRR');
      elsif p_pay_method = 6 then
        l_desc := l_desc || ' تاريخ الحوالة ' || to_char(p_acc_post_date, 'DD-MM-RRRR');
      end if;
    end if;
    return substr(l_desc, 1, 4000);
  exception when no_data_found then
    return p_desc_e;
  end;

  procedure calc_tax(p_trns_id number, p_supplier_id number, p_trns_date date, p_value number,
                     p_tax_code in out number, p_tax_value in out number) is
    l_type  number;
    l_found boolean := false;
  begin
    -- INV_VALUE WHEN-VALIDATE-ITEM -> TAX_LIB_NEW.GET_TAX_VALUE(supplier path): not for payments (TRNS_TYPE 1)
    begin
      select trns_type into l_type from vn_trnstype where id = p_trns_id;
    exception when no_data_found then
      return;
    end;
    if l_type = 1 or p_value is null then
      return;
    end if;
    for t in (select tax_code from tx_taxes_types
               where start_date = (select max(start_date) from tx_taxes_types where start_date <= nvl(p_trns_date, sysdate))
               order by tax_code) loop
      for s in (select tax_code, decode(tax_per, 0, 0, tax_per) tax_per
                  from tx_taxes_suppliers where supplier_code = p_supplier_id and tax_code = t.tax_code) loop
        p_tax_code  := s.tax_code;
        p_tax_value := nvl(s.tax_per, 0) * p_value / 100;
        l_found := true;
      end loop;
    end loop;
    if not l_found then
      p_tax_code  := null;     -- improvement: the form kept the previous supplier's tax; a supplier without a tax row has none
      p_tax_value := null;
    end if;
  end;

  function total_with_tax(p_trns_id number, p_supplier_id number, p_value number, p_tax1 number, p_tax2 number) return number is
    l_type number;
    l_ext  number;
  begin
    select trns_type into l_type from vn_trnstype where id = p_trns_id;
    if l_type = 1 then
      return p_value;                                   -- payments: total = entered value
    end if;
    select nvl(min(ext_supp_flag), 0) into l_ext from tx_taxes_suppliers where tax_code = 1 and supplier_code = p_supplier_id;
    if l_ext = 1 then
      return p_value;                                   -- tax-exempt (external) supplier
    end if;
    return p_value + nvl(p_tax1, 0) + nvl(p_tax2, 0);
  exception when no_data_found then
    return p_value;
  end;

  procedure acc_line(p_acc_number number, p_acc_val number, p_cost_center number, p_cost_center2 number) is
    l_f1  number;
    l_f2  number;
    l_all1 number;
    l_all2 number;
  begin
    -- ACC_VAL WHEN-VALIDATE-ITEM (VAL_ALR)
    if p_acc_val is null or p_acc_val <= 0 then
      err(-20121, 'قيمة الحساب يجب أن تكون أكبر من الصفر');
    end if;
    -- SET_COST / SET_COST2: the last block of the procedure decides - cost centre required when AC_BASIC.ALL_COSTn_FLAG = 1
    -- or AC_MASTER.ACC_COSTn_FLAG = 1 for the account
    begin
      select nvl(acc_cost1_flag, 0), nvl(acc_cost2_flag, 0) into l_f1, l_f2 from ac_master where account_number = p_acc_number;
    exception when no_data_found then
      err(-20122, 'رقم الحساب غير موجود');
    end;
    select nvl(max(all_cost1_flag), 0), nvl(max(all_cost2_flag), 0) into l_all1, l_all2
      from ac_basic where company_code = nvl(num(v('G_COMPANY_CODE')), company_code);
    if (l_all1 = 1 or l_f1 = 1) and p_cost_center is null then
      err(-20123, 'يجب إدخال مركز التكلفة 1 للحساب ' || p_acc_number);
    end if;
    if (l_all2 = 1 or l_f2 = 1) and p_cost_center2 is null then
      err(-20124, 'يجب إدخال مركز التكلفة 2 للحساب ' || p_acc_number);
    end if;
  end;

  function supp_acc_memo(p_trns_id number, p_trns_serial number, p_memo varchar2) return varchar2 is
    l_supp number;
    l_name varchar2(400);
    l_pref varchar2(600);
  begin
    -- VN_MAINTRNS_SUPP_ACC PRE-INSERT: ACC_MEMO := supplier id - supplier name [- memo]
    select m.supplier_id, s.name_a into l_supp, l_name
      from vn_maintrns m left join supplier s on s.code = m.supplier_id
     where m.trns_id = p_trns_id and m.trns_serial = p_trns_serial;
    if l_supp is null then
      return p_memo;
    end if;
    l_pref := l_supp || ' - ' || l_name;
    if p_memo like l_supp || ' - %' then
      return p_memo;                                    -- already prefixed (copied row)
    end if;
    return substr(l_pref || case when p_memo is not null then ' - ' end || p_memo, 1, 800);
  exception when no_data_found then
    return p_memo;
  end;

  function band_supplier(p_trns_id number, p_trns_serial number) return number is
    l number;
  begin
    select supplier_id into l from vn_maintrns where trns_id = p_trns_id and trns_serial = p_trns_serial;
    return l;
  exception when no_data_found then
    return null;
  end;

  -- ------------------------------------------------------------------ shared checks
  function supplier_msg(p_supplier_id number, p_is_new boolean) return varchar2 is
    l_stop   number;
    l_status number;
    l_from   number;
    l_to     number;
    l_pw     number := pw;
  begin
    if p_supplier_id is null then
      return 'يجب إدخال رقم المورد';
    end if;
    begin
      select nvl(stopflag, 0), nvl(supplier_status, 0) into l_stop, l_status from supplier where code = p_supplier_id;
    exception when no_data_found then
      return 'رقم المورد غير موجود';
    end;
    if p_is_new then
      if l_stop = 1 then
        return 'هذا المورد متوقف';                           -- PRE-INSERT
      end if;
      if l_status <> 1 then
        return 'المورد غير فعال ولا يمكن التعامل معه';       -- SUPPLIER record group: NVL(SUPPLIER_STATUS,0) = 1
      end if;
      if l_pw <> 0 then                                   -- SUPPLIER record group: VN_SUPPLIER_PASSWORD range
        begin
          select from_supplier_code, to_supplier_code into l_from, l_to
            from vn_supplier_password where password_number = l_pw and rownum = 1;
        exception when no_data_found then
          l_from := null;
        end;
        if l_from is null or p_supplier_id not between l_from and l_to then
          return 'لا توجد صلاحية على هذا المورد';
        end if;
      end if;
    end if;
    return null;
  end;

  function currency_msg(p_supplier_id number, p_currency_code number, p_currency_rate number) return varchar2 is
    l_cur  number;
    l_name varchar2(200);
  begin
    if p_currency_code is null then
      return 'يجب إدخال رقم العملة';
    end if;
    -- SUPPLIER_ID WHEN-VALIDATE-ITEM sets the currency from the supplier
    begin
      select s.currency_code, c.currency_desc into l_cur, l_name
        from supplier s left join ac_currency c on c.currency_code = s.currency_code
       where s.code = p_supplier_id;
    exception when no_data_found then
      l_cur := null;
    end;
    if l_cur is not null and l_cur <> p_currency_code then
      return 'عملة الحركة يجب أن تكون عملة المورد: ' || l_name;
    end if;
    -- CURRENCY_RATE WHEN-VALIDATE-ITEM
    if p_currency_rate is null or p_currency_rate <= 0 then
      return 'يجب ان يكون معامل التحويل أكبر من 0';
    end if;
    if p_currency_code = 1 and p_currency_rate <> 1 then
      return 'يجب ان يكون معامل التحويل 1';
    end if;
    return null;
  end;

  function date_msg(p_date date, p_supplier_id number, p_check_future boolean default true) return varchar2 is
    l_min   date;
    l_start date;
    l_op    date;
  begin
    if p_date is null then
      return null;
    end if;
    -- TRANSLATE.CHECK_DATE / CHECK_DATE_NEW (system 5): not after today, not before VN_BASIC.MIN_DATE
    if p_check_future and trunc(p_date) > trunc(sysdate) then
      return 'تاريخ الحركة أكبر من تاريخ اليوم';
    end if;
    select min(min_date) into l_min from vn_basic;
    if l_min is null then
      l_min := to_date('01-01-' || (to_number(to_char(sysdate, 'YYYY')) - 1), 'DD-MM-YYYY');
    end if;
    if trunc(p_date) < trunc(l_min) then
      return 'الحد الأدنى لتاريخ الحركة هو ' || to_char(l_min, 'DD/MM/YYYY');
    end if;
    if p_supplier_id is not null then
      -- CHECK_SUPP_INFO: not before the supplier start date
      begin
        select start_date into l_start from supplier where code = p_supplier_id;
      exception when no_data_found then
        l_start := null;
      end;
      if l_start is not null and trunc(p_date) < trunc(l_start) then
        return 'تاريخ الحركة لا يمكن ان يكون اقل من تاريخ فتح المورد';
      end if;
      -- CHECK_OPEN_BAL: not before the supplier opening balance date
      select max(m.trns_date) into l_op
        from vn_maintrns_op m, vn_subtrns_op d
       where m.trns_id = d.trns_id and m.trns_serial = d.trns_serial and d.supplier_id = p_supplier_id;
      if l_op is not null and trunc(p_date) < trunc(l_op) then
        return 'تاريخ الحركة لا يمكن ان يكون اقل من تاريخ الرصيد الافتتاحى للمورد';
      end if;
    end if;
    return null;
  end;

  function locked_msg(p_post_flag number, p_pay_flag number, p_link_flag number, p_action varchar2) return varchar2 is
  begin
    -- CLOSE_POSTED + PRE-UPDATE (POST_ALR2) + WHEN-NEW-RECORD-INSTANCE (LINK_FLAG): read-only documents
    if nvl(p_post_flag, 0) = 1 then
      return 'الحركة الحالية تم ترحيلها و لا يمكن ' || p_action;
    elsif nvl(p_pay_flag, 0) = 1 then
      return 'الحركة الحالية مدفوعة و لا يمكن ' || p_action;
    elsif nvl(p_link_flag, 0) <> 0 then
      return 'الحركة مولدة من نظام آخر و لا يمكن ' || p_action || ' من هذه الشاشة';
    end if;
    return null;
  end;

  -- ------------------------------------------------------------------ page validations
  function check_header(p_form varchar2, p_request varchar2, p_rowid varchar2, p_trns_id varchar2, p_supplier_id varchar2,
                        p_trns_date varchar2, p_acc_post_date varchar2, p_doc_no varchar2, p_currency_code varchar2,
                        p_currency_rate varchar2, p_inv_value varchar2 default null) return varchar2 is
    l_trns_id  number := num(p_trns_id);
    l_supp     number := num(p_supplier_id);
    l_doc      number := num(p_doc_no);
    l_date     date   := dt(p_trns_date);
    l_is_new   boolean := p_request = 'CREATE' or p_rowid is null;
    l_supp_new boolean := l_is_new;
    l_doc_flag number;
    l_lines    number;
    l_msg      varchar2(4000);
    o          vn_maintrns%rowtype;
  begin
    if l_trns_id is null then
      return 'يجب إدخال نوع الحركة';
    end if;
    if type_allowed(p_form, l_trns_id) = 0 then
      return 'نوع الحركة ' || l_trns_id || ' غير مسموح به في هذه الشاشة';
    end if;
    if not l_is_new then
      begin
        select * into o from vn_maintrns where rowid = chartorowid(p_rowid);
      exception when others then
        return 'لم يتم العثور على الحركة، أعد تحميل الصفحة';
      end;
      l_msg := locked_msg(o.post_flag, o.pay_flag, o.link_flag, 'تعديلها');
      if l_msg is not null then
        return l_msg;
      end if;
      if o.trns_id <> l_trns_id then
        return 'لا يمكن تغيير نوع الحركة بعد الحفظ';
      end if;
      if differs(o.supplier_id, l_supp) = 1 then
        l_supp_new := true;
        select count(*) into l_lines from vn_subtrns where trns_id = o.trns_id and trns_serial = o.trns_serial;
        if l_lines > 0 then
          return 'يجب حذف التفاصيل قبل تغيير المورد';      -- SUPPLIER_ID WHEN-VALIDATE-ITEM
        end if;
      end if;
    end if;
    l_msg := supplier_msg(l_supp, l_supp_new);
    if l_msg is not null then return l_msg; end if;
    l_msg := currency_msg(l_supp, num(p_currency_code), num(p_currency_rate));
    if l_msg is not null then return l_msg; end if;
    if l_date is null then
      return 'يجب إدخال تاريخ الحركة';
    end if;
    l_msg := date_msg(l_date, l_supp);
    if l_msg is not null then return l_msg; end if;
    if p_acc_post_date is not null then                                  -- ACC_POST_DATE WHEN-VALIDATE-ITEM
      l_msg := date_msg(dt(p_acc_post_date), l_supp);
      if l_msg is not null then return l_msg; end if;
    end if;
    -- DOC_NO: > 0; required when VN_TRNSTYPE.DOC_FLAG = 1 (TRNS_ID WHEN-VALIDATE-ITEM)
    if l_doc is not null and l_doc <= 0 then
      return 'رقم المستند يجب ان يكون اكبر من الصفر';
    end if;
    select nvl(doc_flag, 0) into l_doc_flag from vn_trnstype where id = l_trns_id;
    if l_doc_flag = 1 and l_doc is null then
      return 'يجب إدخال رقم المستند لهذا النوع من الحركات';
    end if;
    if p_form = 'VNDBTRN' and nvl(num(p_inv_value), 0) <= 0 then          -- INV_VALUE WHEN-VALIDATE-ITEM
      return 'إجمالي الحركة بالعملة يجب ان يكون اكبر من الصفر';
    end if;
    return null;
  end;

  function check_st(p_form varchar2, p_rowid varchar2, p_doc_no varchar2) return varchar2 is
    o vn_maintrns%rowtype;
  begin
    begin
      select * into o from vn_maintrns where rowid = chartorowid(p_rowid);
    exception when others then
      return 'لا يمكن إضافة حركات من هذه الشاشة';
    end;
    if o.post_system is null or type_allowed(p_form, o.trns_id) = 0 then
      return 'هذه الحركة لا تخص هذه الشاشة';
    end if;
    if num(p_doc_no) is not null and num(p_doc_no) <= 0 then
      return 'رقم المستند يجب ان يكون اكبر من الصفر';
    end if;
    return null;
  end;

  -- ------------------------------------------------------------------ GL link (Check_GL_Link)
  procedure check_gl_link(p_trns_id number, p_trns_serial number) is
    h      vn_maintrns%rowtype;
    l_join number;
    l_acct number;
    l_supt number;
    l_acc  number;
    l_sup  number;
    l_cd   number;
    l_disc number;
    l_base number;
    l_mode boolean;
  begin
    select * into h from vn_maintrns where trns_id = p_trns_id and trns_serial = p_trns_serial;
    select nvl(account_joint, 0), nvl(account_type, 0), nvl(supp_account_type, 0) into l_join, l_acct, l_supt
      from vn_trnstype where id = p_trns_id;
    if l_join <> 1 then
      return;
    end if;
    select round(nvl(sum(acc_val), 0), 2) into l_acc from vn_maintrns_acc where trns_id = p_trns_id and trns_serial = p_trns_serial;
    select round(nvl(sum(acc_val), 0), 2) into l_sup from vn_maintrns_supp_acc where trns_id = p_trns_id and trns_serial = p_trns_serial;
    select nvl(sum(currency_diff_value), 0), nvl(sum(disc_value), 0) into l_cd, l_disc
      from vn_subtrns where trns_id = p_trns_id and trns_serial = p_trns_serial;
    l_base := round(nvl(h.inv_value, h.total_value) * nvl(h.currency_rate, 1), 2);
    l_mode := nvl(h.pay_method, 5) = 5 or not has_rap_chk_sys;
    if l_acct = 5 and l_supt = 5 then
      if l_mode and l_sup <> l_acc then
        err(-20131, 'يجب ان يتساوى الدائن مع المدين');
      elsif l_sup < l_base then
        err(-20132, 'يجب ان يكون اجمالي الدائن والمدين اكبر من اجمالي الحركة');
      end if;
    elsif l_acct = 5 and l_supt <> 5 then
      if l_mode and l_acc <> l_base + l_sup then
        err(-20133, 'يجب ادخال حساب الحركة وان يكون مساوي لمجموع لقيمة الحركة + مجموع الحسابات الدائنة'
                    || ' (' || to_char(l_base + l_sup) || ')');
      end if;
    elsif l_acct <> 5 and l_supt = 5 then
      if l_sup <> round(l_base + l_acc - l_cd + nvl(h.currency_rate, 0) * l_disc, 2) then
        err(-20134, 'يجب ادخال حساب المورد وان يكون مساوي لمجموع لقيمة الحركة + مجموع الحسابات المدينة'
                    || ' (' || to_char(round(l_base + l_acc - l_cd + nvl(h.currency_rate, 0) * l_disc, 2)) || ')');
      end if;
    elsif l_sup <> l_acc then
      err(-20131, 'يجب ان يتساوى الدائن مع المدين');
    end if;
  end;

  -- ------------------------------------------------------------------ VNDBTRN: payment lines
  procedure settle_lines(h vn_maintrns%rowtype, p_table varchar2 default 'VN_SUBTRNS') is
    l_cnt   number;
    l_inv   vn_subtrns%rowtype;
    l_ihdr  vn_maintrns%rowtype;
    l_paid  number;
    l_ids   varchar2(200);
  begin
    for l in (select s.rowid rid, s.* from vn_subtrns s
               where s.trns_id = h.trns_id and s.trns_serial = h.trns_serial order by s.bill_seq) loop
      l_ids := nvl(l.bill_id1, l.inv_trns_id || '/' || l.inv_trns_serial);
      if nvl(l.total_value, 0) <= 0 then                                -- VN_SUBTRNS PRE-INSERT / TOTAL_VALUE WVI
        err(-20141, 'قيمة الفاتورة يجب ان تكون أكبر من الصفر: ' || l_ids);
      end if;
      if nvl(l.disc_value, 0) < 0 then
        err(-20142, 'قيمة الخصم يجب ان تكون اكبر من الصفر: ' || l_ids);
      end if;
      if nvl(l.disc_value, 0) > l.total_value then
        err(-20143, 'قيمة الخصم لابد أن تكون أقل من القيمة المدخلة للفاتورة: ' || l_ids);
      end if;
      if l.bill_id1 is null and l.inv_trns_id is null then
        err(-20144, 'يجب إدخال رقم الفاتورة أو رقم حركة الفاتورة في سطور السداد');
      end if;
      -- BILL record group: open credit-invoice lines of the same supplier and currency, not stopped
      select count(*) into l_cnt
        from vn_subtrns s join vn_maintrns m on m.trns_id = s.trns_id and m.trns_serial = s.trns_serial
       where m.trns_id in (select id from vn_trnstype where effect = 1)
         and m.supplier_id = h.supplier_id
         and m.currency_code = h.currency_code
         and nvl(s.stop_flag, 0) = 0
         and (l.inv_trns_id is null or s.trns_id = l.inv_trns_id)
         and (l.inv_trns_serial is null or s.trns_serial = l.inv_trns_serial)
         and (l.inv_bill_seq is null or s.bill_seq = l.inv_bill_seq)
         and (l.bill_id1 is null or s.bill_id1 = l.bill_id1)
         and (l.bill_id2 is null or s.bill_id2 = l.bill_id2);
      if l_cnt = 0 then
        err(-20145, 'الفاتورة غير موجودة لهذا المورد بنفس العملة أو موقوف سدادها: ' || l_ids);
      elsif l_cnt > 1 then
        err(-20146, 'رقم الفاتورة ' || l_ids || ' يطابق أكثر من فاتورة، أدخل رقم حركة الفاتورة ومسلسلها');
      end if;
      select s.* into l_inv
        from vn_subtrns s join vn_maintrns m on m.trns_id = s.trns_id and m.trns_serial = s.trns_serial
       where m.trns_id in (select id from vn_trnstype where effect = 1)
         and m.supplier_id = h.supplier_id
         and m.currency_code = h.currency_code
         and nvl(s.stop_flag, 0) = 0
         and (l.inv_trns_id is null or s.trns_id = l.inv_trns_id)
         and (l.inv_trns_serial is null or s.trns_serial = l.inv_trns_serial)
         and (l.inv_bill_seq is null or s.bill_seq = l.inv_bill_seq)
         and (l.bill_id1 is null or s.bill_id1 = l.bill_id1)
         and (l.bill_id2 is null or s.bill_id2 = l.bill_id2);
      select * into l_ihdr from vn_maintrns where trns_id = l_inv.trns_id and trns_serial = l_inv.trns_serial;
      -- residual = invoice value - everything already paid on it by other payment lines (VN_SUBTRNS_PAYED_VALUE)
      select nvl(sum(total_value), 0) into l_paid
        from vn_subtrns
       where inv_trns_id = l_inv.trns_id and inv_trns_serial = l_inv.trns_serial and inv_bill_seq = l_inv.bill_seq
         and rowid <> l.rid;
      if round(l.total_value, 2) > round(nvl(l_inv.total_value, 0) - l_paid, 2) then
        err(-20147, 'القيمة يجب أن تكون أصغر من القيمة المتبقية فى الفاتورة ' || l_ids || ' (' || to_char(nvl(l_inv.total_value, 0) - l_paid) || ')');
      end if;
      if h.currency_code = 1 and nvl(l.currency_diff_value, 0) <> 0 then
        err(-20148, 'لا يجب ادخال قيمة فروق العملة في حالة العملة ريال');
      end if;
      update vn_subtrns
         set inv_trns_id         = l_inv.trns_id,
             inv_trns_serial     = l_inv.trns_serial,
             inv_bill_seq        = l_inv.bill_seq,
             bill_id1            = l_inv.bill_id1,
             bill_id2            = l_inv.bill_id2,
             inv_date            = l_ihdr.trns_date,
             inv_supplier_ref    = nvl(inv_supplier_ref, l_ihdr.supplier_ref),
             pay_type_code       = nvl(pay_type_code, l_inv.pay_type_code),
             net_value           = total_value - nvl(disc_value, 0),
             -- TOTAL_VALUE WVI: currency difference = value * (payment rate - invoice rate)
             currency_diff_value = nvl(currency_diff_value, total_value * nvl(h.currency_rate, 1) - total_value * nvl(l_ihdr.currency_rate, 1))
       where rowid = l.rid;
    end loop;
  end;

  -- VN_SUBTRNS PRE-INSERT ("UPDATE VN_SUBTRNS SET RESIDUAL_VALUE = RESIDUAL_VALUE - :TOTAL_VALUE" on the paid invoice line) and
  -- PRE-DELETE (DELETE_DETAIL_EFFECT: "+ :TOTAL_VALUE"): the residual of every invoice line paid by this document now or before
  -- the save (committed lines, flashback query) is set to invoice value - all payments (VN_SUBTRNS_PAYED_VALUE), which is the
  -- value the legacy increments give when the stored residual was right.
  procedure refresh_invoice_residuals(h vn_maintrns%rowtype) is
    type t_key is record (tid number, tser number, seq number);
    type t_keys is table of t_key;
    l_keys t_keys;
    l_old  t_keys := t_keys();
    l_paid number;
    procedure one(k t_key) is
    begin
      if k.tid is null then return; end if;
      l_paid := vn_subtrns_payed_value(k.tid, k.tser, k.seq);
      update vn_subtrns set residual_value = nvl(total_value, 0) - l_paid
       where trns_id = k.tid and trns_serial = k.tser and bill_seq = k.seq
         and decode(residual_value, nvl(total_value, 0) - l_paid, 0, 1) = 1;
    end;
  begin
    select inv_trns_id, inv_trns_serial, inv_bill_seq bulk collect into l_keys
      from vn_subtrns where trns_id = h.trns_id and trns_serial = h.trns_serial and inv_trns_id is not null;
    begin
      select inv_trns_id, inv_trns_serial, inv_bill_seq bulk collect into l_old
        from vn_subtrns as of timestamp systimestamp
       where trns_id = h.trns_id and trns_serial = h.trns_serial and inv_trns_id is not null;
    exception when others then
      l_old := t_keys();                      -- no committed state (new document)
    end;
    for i in 1 .. l_keys.count loop one(l_keys(i)); end loop;
    for i in 1 .. l_old.count loop one(l_old(i)); end loop;
  end;

  procedure after_save_dbtrn(h vn_maintrns%rowtype, p_request varchar2) is
    l_net     number;
    l_disc    number;
    l_cd      number;
    l_cnt     number;
    l_single  number;
    l_max     number;
    l_flag    number;
    l_band    number;
    l_bands   number;
    l_items   number;
    l_type    number;
    l_effect  number;
  begin
    settle_lines(h);
    refresh_invoice_residuals(h);
    select nvl(sum(net_value), 0), nvl(sum(disc_value), 0), nvl(sum(currency_diff_value), 0), count(*)
      into l_net, l_disc, l_cd, l_cnt
      from vn_subtrns where trns_id = h.trns_id and trns_serial = h.trns_serial;
    -- VN_SUBTRNS PRE-INSERT / VN_MAINTRNS PRE-UPDATE: paid invoices may not exceed the payment (except method 3 "مبلغ مدين")
    if nvl(h.bill_pay_method, 1) <> 3 and round(nvl(h.total_value, 0), 2) < round(l_net, 2) then
      err(-20151, 'قيمة الفواتير المسددة يجب أن تكون أقل من القيمة الكلية للسداد');
    end if;
    -- SUPPLIER.SINGLE_PAY: one invoice per payment
    select nvl(max(single_pay), 0) into l_single from supplier where code = h.supplier_id;
    if l_single = 1 and l_cnt > 1 then
      err(-20152, 'السداد يحتوي على اكثر من فاتوره بالفعل');
    end if;
    -- header aggregates maintained by the legacy line triggers
    update vn_maintrns
       set disc_value = l_disc,
           currency_diff_value = l_cd,
           residual_value = nvl(total_value, 0) - l_net
     where trns_id = h.trns_id and trns_serial = h.trns_serial;
    -- PRE-INSERT: payment linked to a purchase order may not exceed its remaining value
    if h.po_trns_type_code is not null and get_pr_order_val(h.po_trns_type_code, h.po_trns_serial) < 0 then
      err(-20153, 'القيمة اكبر من القيمة المتبقية للسداد بامر الشراء');
    end if;
    -- INV_VALUE WHEN-VALIDATE-ITEM: USERS.MAX_PAYMENT
    select max(max_payment) into l_max from users where users_code = num(v('G_USER_CODE'));
    if nvl(l_max, 0) <> 0 and l_max < nvl(h.total_value, 0) * nvl(h.currency_rate, 1) then
      err(-20154, 'الحد الاقصى المسموح به للسداد للمستخدم هو  ' || l_max);
    end if;
    -- contract bands (TAB4) exist only when VN_BASIC.CONTRACT_FLAG = 1; their total must equal the transaction total
    select nvl(max(contract_flag), 0) into l_flag from vn_basic;
    select count(*), nvl(sum(band_value), 0) into l_bands, l_band
      from vn_subtrns_band where trns_id = h.trns_id and trns_serial = h.trns_serial;
    if l_bands > 0 and l_flag = 0 then
      err(-20155, 'بنود عقود الموردين غير مفعلة في إعدادات الموردين');
    elsif l_flag = 1 and l_band > 0 and l_band <> nvl(h.total_value, 0) then
      err(-20156, 'إجمالي الحركة يجب أن يساوي مجموع البنود المسددة');
    end if;
    -- item discounts (TAB5) only for debit settlements (EFFECT 0, TRNS_TYPE 4)
    select count(*) into l_items from vn_subtrns_items where trns_id = h.trns_id and trns_serial = h.trns_serial;
    if l_items > 0 then
      select effect, trns_type into l_effect, l_type from vn_trnstype where id = h.trns_id;
      if not (l_effect = 0 and l_type = 4) then
        err(-20157, 'خصومات الأصناف متاحة لحركات التسوية المدينة فقط');
      end if;
      for i in (select rowid rid, x.* from vn_subtrns_items x where trns_id = h.trns_id and trns_serial = h.trns_serial) loop
        if nvl(i.disc_value, 0) < 0 then
          err(-20158, 'ادخل قيمة اكبر من او تساوى صفر');
        end if;
        if i.disc_ratio is not null and (i.disc_ratio < 0 or i.disc_ratio > 100) then
          err(-20159, 'أدخل رقم بقيمة تبدأ من الصفر');
        end if;
        select count(*) into l_cnt from vn_subtrns_items
         where trns_id = h.trns_id and trns_serial = h.trns_serial and rowid <> i.rid
           and bill_id1 = i.bill_id1 and bill_id2 = i.bill_id2 and item_code = i.item_code;
        if l_cnt > 0 then
          err(-20160, 'فاتورة مكررة: ' || i.bill_id1 || '-' || i.bill_id2 || '-' || i.item_code);   -- CHECK_REPEAT
        end if;
      end loop;
      select nvl(sum(disc_value), 0) into l_disc from vn_subtrns_items where trns_id = h.trns_id and trns_serial = h.trns_serial;
      if round(nvl(h.total_value, 0), 2) < round(l_disc, 2) then
        err(-20151, 'قيمة الفواتير المسددة يجب أن تكون أقل من القيمة الكلية للسداد');
      end if;
    end if;
    if p_request = 'SAVE' then
      check_gl_link(h.trns_id, h.trns_serial);
    end if;
  end;

  -- ------------------------------------------------------------------ VNCRTRN: invoice lines
  procedure after_save_crtrn(h vn_maintrns%rowtype, p_request varchar2) is
    l_min      date;
    l_max      date;
    l_days     number;
    l_start    date;
    l_op       date;
    l_next     number;
    l_cnt      number;
    l_total    number;
    l_tax_code number;
    l_tax1     number;
    l_paid     number;
    l_orphans  number;
  begin
    select min(min_date), min(max_date) into l_min, l_max from vn_basic;
    select nvl(max(due_days), 0), max(start_date) into l_days, l_start from supplier where code = h.supplier_id;
    select max(m.trns_date) into l_op from vn_maintrns_op m, vn_subtrns_op d
     where m.trns_id = d.trns_id and m.trns_serial = d.trns_serial and d.supplier_id = h.supplier_id;
    for l in (select s.rowid rid, s.* from vn_subtrns s
               where s.trns_id = h.trns_id and s.trns_serial = h.trns_serial order by s.bill_seq) loop
      if nvl(l.inv_value, l.total_value) is null or nvl(l.inv_value, l.total_value) <= 0 then
        err(-20161, 'قيمة الفاتورة يجب ان تكون أكبر من الصفر');
      end if;
      -- invoice number: BILL_ID2 = supplier, BILL_ID1 = next number of that supplier ("SELECT NVL(MAX(BILL_ID1),0) FROM VN_SUBTRNS WHERE BILL_ID2 = :b1")
      if l.bill_id2 is null or l.bill_id1 is null then
        select nvl(max(to_number(bill_id1 default null on conversion error)), 0) + 1 into l_next
          from vn_subtrns where bill_id2 = nvl(l.bill_id2, to_char(h.supplier_id));
        update vn_subtrns
           set bill_id2 = nvl(bill_id2, to_char(h.supplier_id)),
               bill_id1 = nvl(bill_id1, to_char(l_next))
         where rowid = l.rid;
      end if;
      -- VN_SUBTRNS invoice dates (INV_DATE WVI, DUE_DATE = INV_DATE + SUPPLIER.DUE_DAYS)
      update vn_subtrns
         set inv_date = nvl(inv_date, h.trns_date),
             due_date = nvl(due_date, nvl(inv_date, h.trns_date) + l_days),
             pay_type_code = nvl(pay_type_code, nvl(h.pay_type_code, default_pay_type))
       where rowid = l.rid;
      for c in (select * from vn_subtrns where rowid = l.rid) loop
        if l_min is not null and trunc(c.inv_date) < trunc(l_min) then
          err(-20162, 'الحد الأدنى لتاريخ الحركة هو ' || to_char(l_min, 'DD/MM/YYYY'));
        end if;
        if l_max is not null and trunc(c.inv_date) > trunc(l_max) then
          err(-20163, 'الحد الأقصى لتاريخ الحركة هو ' || to_char(l_max, 'DD/MM/YYYY'));
        end if;
        if l_start is not null and trunc(c.due_date) < trunc(l_start) then
          err(-20164, 'تاريخ الاستحقاق لا يمكن ان يكون اقل من تاريخ فتح المورد');
        end if;
        if l_op is not null and trunc(c.due_date) < trunc(l_op) then
          err(-20165, 'تاريخ الاستحقاق لا يمكن ان يكون اقل من تاريخ الرصيد الافتتاحى للمورد');
        end if;
        -- same invoice number twice for the supplier
        select count(*) into l_cnt
          from vn_subtrns s join vn_maintrns m on m.trns_id = s.trns_id and m.trns_serial = s.trns_serial
         where m.trns_id in (select id from vn_trnstype where effect = 1)
           and m.supplier_id = h.supplier_id
           and s.bill_id1 = c.bill_id1 and s.bill_id2 = c.bill_id2
           and s.rowid <> l.rid;
        if l_cnt > 0 then
          err(-20166, 'فاتورة مكررة: ' || c.bill_id1);
        end if;
        -- line value: TOTAL_VALUE = INV_VALUE + VAT (GET_TAX_VALUE on the line) unless entered as total only
        l_tax_code := c.tax_code1;
        l_tax1 := c.tax_value1;
        if c.inv_value is not null then
          calc_tax(h.trns_id, h.supplier_id, h.trns_date, c.inv_value, l_tax_code, l_tax1);
          l_total := total_with_tax(h.trns_id, h.supplier_id, c.inv_value, l_tax1, c.tax_value2);
        else
          l_total := c.total_value;
        end if;
        l_paid := vn_subtrns_payed_value(c.trns_id, c.trns_serial, c.bill_seq);   -- outside the UPDATE (mutating table)
        update vn_subtrns
           set tax_code1 = l_tax_code,
               tax_value1 = l_tax1,
               total_value = l_total,
               inv_value = nvl(inv_value, l_total),
               residual_value = l_total - l_paid
         where rowid = l.rid;
      end loop;
    end loop;
    -- deleted invoice lines must not leave payments pointing at them (legacy deleted those payments; here it is refused)
    select count(*) into l_orphans
      from vn_subtrns p
     where p.inv_trns_id = h.trns_id and p.inv_trns_serial = h.trns_serial
       and not exists (select 1 from vn_subtrns i where i.trns_id = p.inv_trns_id and i.trns_serial = p.inv_trns_serial and i.bill_seq = p.inv_bill_seq);
    if l_orphans > 0 then
      err(-20167, 'لا يمكن حذف فاتورة تم سداد جزء منها، احذف السداد أولاً');
    end if;
    select count(*), sum(total_value) into l_cnt, l_total from vn_subtrns where trns_id = h.trns_id and trns_serial = h.trns_serial;
    if p_request = 'SAVE' and l_cnt = 0 then
      err(-20168, 'لابد من إدخال فواتير الحركة');
    end if;
    if l_cnt > 0 then
      update vn_maintrns set total_value = l_total where trns_id = h.trns_id and trns_serial = h.trns_serial;   -- TRNS_TOTAL
    end if;
    if p_request = 'SAVE' then
      check_gl_link(h.trns_id, h.trns_serial);
    end if;
  end;

  procedure after_save(p_form varchar2, p_rowid varchar2, p_request varchar2) is
    h vn_maintrns%rowtype;
  begin
    if p_rowid is null then
      return;
    end if;
    select * into h from vn_maintrns where rowid = chartorowid(p_rowid);
    if p_form = 'VNDBTRN' then
      after_save_dbtrn(h, p_request);
    elsif p_form = 'VNCRTRN' then
      after_save_crtrn(h, p_request);
    end if;
  exception when no_data_found then
    null;
  end;

  procedure on_delete(p_form varchar2, p_trns_id varchar2, p_trns_serial varchar2, p_post_flag varchar2,
                      p_pay_flag varchar2, p_link_flag varchar2 default null) is
    l_msg  varchar2(4000);
    l_lot  number;
    l_post number;
    l_pay  number;
    l_link number;
  begin
    -- PRE-DELETE: posted / paid / generated documents cannot be deleted. The header is already deleted in this transaction when
    -- after-save runs, so the committed row is read with a flashback query; the page values are the fallback.
    begin
      select post_flag, pay_flag, link_flag into l_post, l_pay, l_link
        from vn_maintrns as of timestamp systimestamp
       where trns_id = num(p_trns_id) and trns_serial = num(p_trns_serial);
    exception when others then
      null;
    end;
    l_msg := locked_msg(greatest(nvl(l_post, 0), nvl(num(p_post_flag), 0)), greatest(nvl(l_pay, 0), nvl(num(p_pay_flag), 0)),
                        greatest(nvl(l_link, 0), nvl(num(p_link_flag), 0)), 'حذفها');
    if l_msg is not null then
      err(-20171, l_msg);
    end if;
    if p_form = 'VNCRTRN' then
      select count(*) into l_lot from pr_income_lot where vn_trns_id = num(p_trns_id) and vn_trns_serial = num(p_trns_serial);
      if l_lot > 0 then
        err(-20172, 'الحركة مرتبطة برسالة واردة و لا يمكن حذفها');
      end if;
    end if;
    -- PRE-DELETE "default relation" section: remove the detail lines that have no foreign key to the header
    delete from vn_maintrns_supp_acc a
     where a.trns_id = num(p_trns_id) and a.trns_serial = num(p_trns_serial)
       and not exists (select 1 from vn_maintrns m where m.trns_id = a.trns_id and m.trns_serial = a.trns_serial);
    -- wave 3b: the page deletes the payment lines before the header (generator cascade, the legacy PRE-DELETE); the legacy line
    -- delete (DELETE_DETAIL_EFFECT) gave the paid invoices their residual back: recompute it from the committed lines (flashback)
    if p_form = 'VNDBTRN' then
      declare
        h vn_maintrns%rowtype;
      begin
        h.trns_id := num(p_trns_id);
        h.trns_serial := num(p_trns_serial);
        refresh_invoice_residuals(h);
      end;
    end if;
  end;

  -- ------------------------------------------------------------------ VNCHECKPAY
  procedure checkpay_supplier_info(p_supplier_id number, p_supplier_bal in out number, p_db_cr_flag in out varchar2,
                                   p_db_cr_flag_e in out varchar2, p_check_hold in out number, p_currency_code in out number,
                                   p_currency_rate in out number, p_resp_code in out number) is
    l_db  number;
    l_cr  number;
    l_bal number;
  begin
    if p_supplier_id is null then
      return;
    end if;
    -- SUPPLIER_ID WHEN-VALIDATE-ITEM: balance = credit invoice lines - debit transactions
    select nvl(sum(nvl(total_value, 0) + nvl(disc_value, 0)), 0) into l_db
      from vn_maintrns mn, vn_trnstype typ where mn.trns_id = typ.id and typ.effect = 0 and mn.supplier_id = p_supplier_id;
    select nvl(sum(nvl(s.total_value, 0) + nvl(s.disc_value, 0)), 0) into l_cr
      from vn_maintrns mn, vn_trnstype typ, vn_subtrns s
     where mn.trns_id = typ.id and mn.trns_id = s.trns_id and mn.trns_serial = s.trns_serial
       and typ.effect = 1 and mn.supplier_id = p_supplier_id;
    l_bal := l_cr - l_db;
    p_db_cr_flag   := case when l_bal > 0 then 'د' else 'م' end;
    p_db_cr_flag_e := case when l_bal > 0 then 'C' else 'D' end;
    p_supplier_bal := abs(l_bal);
    -- cheques / cash payments not yet paid out
    select nvl(sum(nvl(total_value, 0)), 0) into p_check_hold
      from vn_maintrns
     where nvl(pay_flag, 0) = 0 and nvl(pay_method, 0) in (2, 4)
       and trns_id in (select id from vn_trnstype where trns_type = 1) and supplier_id = p_supplier_id;
    if p_currency_code is null then
      select max(s.currency_code), max(c.rate) into p_currency_code, p_currency_rate
        from supplier s left join ac_currency c on c.currency_code = s.currency_code where s.code = p_supplier_id;
    end if;
    if p_resp_code is null then
      p_resp_code := supplier_resp(p_supplier_id);
    end if;
  end;

  function check_checkpay(p_request varchar2, p_rowid varchar2, p_supplier_id varchar2, p_from_date varchar2, p_to_date varchar2,
                          p_due_date varchar2, p_doc_no varchar2, p_currency_code varchar2, p_currency_rate varchar2,
                          p_due_disc varchar2, p_auth_flag varchar2) return varchar2 is
    l_supp   number := num(p_supplier_id);
    l_is_new boolean := p_request = 'CREATE' or p_rowid is null;
    l_new_s  boolean := l_is_new;
    l_auth   number := nvl(num(p_auth_flag), 0);
    l_old_a  number := 0;
    l_right  number;
    l_msg    varchar2(4000);
    l_disc   number := num(p_due_disc);
    o        vn_maintrns_check%rowtype;
  begin
    if not l_is_new then
      begin
        select * into o from vn_maintrns_check where rowid = chartorowid(p_rowid);
      exception when others then
        return 'لم يتم العثور على إذن الصرف، أعد تحميل الصفحة';
      end;
      l_old_a := nvl(o.auth_flag, 0);
      if l_old_a = 1 then
        return 'الحركة الحالية تم اعتمادها و لا يمكن تعديلها';
      end if;
      if differs(o.supplier_id, l_supp) = 1 then
        l_new_s := true;
        select count(*) into l_right from vn_subtrns_check where serial = o.serial;
        if l_right > 0 then
          return 'يجب حذف التفاصيل قبل تغيير المورد';
        end if;
      end if;
    end if;
    l_msg := supplier_msg(l_supp, l_new_s);
    if l_msg is not null then return l_msg; end if;
    l_msg := currency_msg(l_supp, nvl(num(p_currency_code), 1), nvl(num(p_currency_rate), 1));
    if l_msg is not null then return l_msg; end if;
    for d in (select dt(p_from_date) d from dual union all select dt(p_to_date) from dual union all select dt(p_due_date) from dual) loop
      if d.d is not null then
        l_msg := date_msg(d.d, l_supp, false);
        if l_msg is not null then
          return replace(l_msg, 'تاريخ الحركة لا يمكن ان يكون اقل من تاريخ فتح المورد', 'تاريخ الاستحقاق لا يمكن ان يكون اقل من تاريخ فتح المورد');
        end if;
      end if;
    end loop;
    if num(p_doc_no) is not null and num(p_doc_no) <= 0 then
      return 'رقم المستند يجب ان يكون اكبر من الصفر';
    end if;
    if l_disc is not null and (l_disc < 0 or l_disc >= 100) then
      return 'أدخل رقم بقيمة تبدأ من الصفر و أقل من المئة';
    end if;
    if l_auth = 1 and l_old_a = 0 then
      -- approval levels USERS.VN_PAY_AUTH1..6 (ACCEPT_AUTH_BTNn): only an approver may mark the request as authorised
      select count(*) into l_right from users
       where users_code = num(v('G_USER_CODE'))
         and 1 in (nvl(vn_pay_auth1, 0), nvl(vn_pay_auth2, 0), nvl(vn_pay_auth3, 0), nvl(vn_pay_auth4, 0), nvl(vn_pay_auth5, 0), nvl(vn_pay_auth6, 0));
      if l_right = 0 then
        return 'ليس لديك صلاحية اعتماد اذونات صرف الشيكات';
      end if;
    end if;
    return null;
  end;

  procedure after_save_checkpay(p_rowid varchar2, p_request varchar2) is
    h        vn_maintrns_check%rowtype;
    l_cnt    number;
    l_inv    vn_subtrns%rowtype;
    l_ihdr   vn_maintrns%rowtype;
    l_paid   number;
    l_req    number;
    l_net    number;
    l_single number;
    l_ids    varchar2(200);
  begin
    if p_rowid is null then
      return;
    end if;
    select * into h from vn_maintrns_check where rowid = chartorowid(p_rowid);
    for l in (select s.rowid rid, s.* from vn_subtrns_check s where s.serial = h.serial order by s.bill_seq) loop
      l_ids := nvl(l.bill_id1, l.inv_trns_id || '/' || l.inv_trns_serial);
      if nvl(l.total_value, 0) <= 0 then
        err(-20181, 'القيمة يجب أن تكون أكبر من الصفر: ' || l_ids);
      end if;
      if nvl(l.disc_value, 0) < 0 then
        err(-20182, 'قيمة الخصم يجب ان تكون اكبر من الصفر');
      end if;
      if nvl(l.disc_value, 0) > l.total_value then
        err(-20183, 'قيمة الخصم لابد أن تكون أقل من القيمة المدخلة للفاتورة');
      end if;
      if l.bill_id1 is null and l.inv_trns_id is null then
        err(-20184, 'يجب إدخال رقم الفاتورة في تفاصيل الفواتير');
      end if;
      select count(*) into l_cnt
        from vn_subtrns s join vn_maintrns m on m.trns_id = s.trns_id and m.trns_serial = s.trns_serial
       where m.trns_id in (select id from vn_trnstype where effect = 1)
         and m.supplier_id = h.supplier_id
         and m.currency_code = nvl(h.currency_code, m.currency_code)
         and nvl(s.stop_flag, 0) = 0
         and (l.inv_trns_id is null or s.trns_id = l.inv_trns_id)
         and (l.inv_trns_serial is null or s.trns_serial = l.inv_trns_serial)
         and (l.inv_bill_seq is null or s.bill_seq = l.inv_bill_seq)
         and (l.bill_id1 is null or s.bill_id1 = l.bill_id1)
         and (l.bill_id2 is null or s.bill_id2 = l.bill_id2);
      if l_cnt = 0 then
        err(-20185, 'الفاتورة غير موجودة لهذا المورد بنفس العملة أو موقوف سدادها: ' || l_ids);
      elsif l_cnt > 1 then
        err(-20186, 'رقم الفاتورة ' || l_ids || ' يطابق أكثر من فاتورة');
      end if;
      select s.* into l_inv
        from vn_subtrns s join vn_maintrns m on m.trns_id = s.trns_id and m.trns_serial = s.trns_serial
       where m.trns_id in (select id from vn_trnstype where effect = 1)
         and m.supplier_id = h.supplier_id
         and m.currency_code = nvl(h.currency_code, m.currency_code)
         and nvl(s.stop_flag, 0) = 0
         and (l.inv_trns_id is null or s.trns_id = l.inv_trns_id)
         and (l.inv_trns_serial is null or s.trns_serial = l.inv_trns_serial)
         and (l.inv_bill_seq is null or s.bill_seq = l.inv_bill_seq)
         and (l.bill_id1 is null or s.bill_id1 = l.bill_id1)
         and (l.bill_id2 is null or s.bill_id2 = l.bill_id2);
      select * into l_ihdr from vn_maintrns where trns_id = l_inv.trns_id and trns_serial = l_inv.trns_serial;
      -- residual = invoice - payments (VN_SUBTRNS_PAYED_VALUE) - other cheque requests (VN_SUBTRNS_CHECK_PAYED_VALUE)
      l_paid := vn_subtrns_payed_value(l_inv.trns_id, l_inv.trns_serial, l_inv.bill_seq);
      select nvl(sum(total_value), 0) into l_req
        from vn_subtrns_check
       where inv_trns_id = l_inv.trns_id and inv_trns_serial = l_inv.trns_serial and inv_bill_seq = l_inv.bill_seq
         and rowid <> l.rid;
      if round(l.total_value, 2) > round(nvl(l_inv.total_value, 0) - l_paid - l_req, 2) then
        err(-20187, 'القيمة المتبقية بالفاتورة أصغر من القيمة المدخلة للسداد: ' || l_ids);
      end if;
      if nvl(h.currency_code, 1) = 1 and nvl(l.currency_diff_value, 0) <> 0 then
        err(-20188, 'لا يجب ادخال قيمة في حالة العملة ريال');
      end if;
      update vn_subtrns_check
         set inv_trns_id      = l_inv.trns_id,
             inv_trns_serial  = l_inv.trns_serial,
             inv_bill_seq     = l_inv.bill_seq,
             bill_id1         = l_inv.bill_id1,
             bill_id2         = l_inv.bill_id2,
             inv_date         = l_ihdr.trns_date,
             inv_supplier_ref = nvl(inv_supplier_ref, l_ihdr.supplier_ref),
             pay_type_code    = nvl(pay_type_code, l_inv.pay_type_code),
             residual_value   = nvl(l_inv.total_value, 0) - l_paid - l_req,
             net_value        = total_value - nvl(disc_value, 0)
       where rowid = l.rid;
    end loop;
    select count(*), nvl(sum(net_value), 0) into l_cnt, l_net from vn_subtrns_check where serial = h.serial;
    select nvl(max(single_pay), 0) into l_single from supplier where code = h.supplier_id;
    if l_single = 1 and l_cnt > 1 then
      err(-20189, 'السداد يحتوي على اكثر من فاتوره بالفعل');
    end if;
    if h.check_amount is not null and round(l_net, 2) > round(h.check_amount, 2) then
      err(-20190, 'خطأ في اجمالي مبالغ الفواتير: مجموع الفواتير أكبر من مبلغ الدفعة');
    end if;
  exception when no_data_found then
    null;
  end;

  procedure on_delete_checkpay(p_serial varchar2, p_auth_flag varchar2) is
    l_auth number;
  begin
    begin
      select auth_flag into l_auth from vn_maintrns_check as of timestamp systimestamp where serial = num(p_serial);   -- committed row
    exception when others then
      null;
    end;
    if nvl(l_auth, 0) = 1 or nvl(num(p_auth_flag), 0) = 1 then
      err(-20191, 'الحركة الحالية تم اعتمادها و لا يمكن حذفها');
    end if;
  end;

end app_rules_vn;
/
show errors package app_rules_vn
show errors package body app_rules_vn
